name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Unzip project
        run: unzip ChulaXuta_Android_Project_v1_3_CAPITAIN.zip -d project

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - uses: android-actions/setup-android@v3

      - uses: gradle/actions/setup-gradle@v4

      - name: Build APK
        run: |
          cd project
          find . -name gradlew
          chmod +x $(find . -name gradlew)
          cd $(find . -type f -name gradlew | head -n 1 | xargs dirname)
          ./gradlew assembleDebug

      - uses: actions/upload-artifact@v4
        with:
          name: ChutaXuta-Capitain-APK
          path: project/**/app/build/outputs/apk/debug/*.apk
